backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Страницы"
    files:
      - label: "О школе"
        name: "school"
        file: "data/school.json"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Текст", name: "body", widget: "markdown" }

      - label: "Расписание"
        name: "schedule"
        file: "data/schedule.json"
        fields:
          - { label: "Ссылка на Google Docs (embed/publish URL)", name: "gdocs_url", widget: "string", hint: "Вставьте ссылку на документ Google с включённым доступом по ссылке" }

      - label: "Zoom-комнаты"
        name: "zoom"
        file: "data/zoom.json"
        fields:
          - label: "Комнаты"
            name: "rooms"
            widget: "list"
            fields:
              - { label: "Название", name: "title", widget: "string" }
              - { label: "Ссылка (URL)", name: "url", widget: "string" }
              - { label: "Пароль (необязательно)", name: "password", widget: "string", required: false }

      - label: "Страница записи (тексты)"
        name: "enroll"
        file: "data/contact.json"
        fields:
          - { label: "Заголовок", name: "heading", widget: "string", default: "Запись" }
          - { label: "Описание", name: "description", widget: "markdown", default: "Заполните форму, и мы свяжемся с вами." }
