backend:
  name: github
  repo: ВАШ_GITHUB_ЛОГИН/ВАШ_РЕПОЗИТОРИЙ   # ← сюда подставьте своё
  branch: main                            # если у вас master, то замените на master

media_folder: "images/uploads"            # картинки будут загружаться сюда в репозитории
public_folder: "/images/uploads"          # и отдаваться на сайте

collections:
  - name: "school"
    label: "О школе"
    files:
      - file: "content/school.json"
        label: "Страница школы"
        name: "schoolPage"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Описание", name: "body", widget: "text" }

  - name: "enroll"
    label: "Запись"
    files:
      - file: "content/enroll.json"
        label: "Форма записи"
        name: "enrollPage"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Инструкция", name: "instructions", widget: "text" }

  - name: "schedule"
    label: "Расписание"
    files:
      - file: "content/schedule.json"
        label: "Файл с расписанием"
        name: "schedulePage"
        fields:
          - { label: "Ссылка на Google Docs", name: "url", widget: "string" }

  - name: "zoom"
    label: "Zoom-ссылки"
    files:
      - file: "content/zoom.json"
        label: "Ссылки для входа"
        name: "zoomPage"
        fields:
          - { label: "Ссылки", name: "links", widget: "list", fields: [{ label: "Название", name: "name", widget: "string" }, { label: "URL", name: "url", widget: "string" }] }
